"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EventBots = exports.ScavBots = exports.PMCBots = exports.SpecialBots = exports.FollowerBots = exports.BossBots = void 0;
var BossBots;
(function (BossBots) {
    BossBots["BOSSBOAR"] = "bossboar";
    BossBots["BOSSBULLY"] = "bossbully";
    BossBots["BOSSGLUHAR"] = "bossgluhar";
    BossBots["BOSSKILLA"] = "bosskilla";
    BossBots["BOSSKOJANIY"] = "bosskojaniy";
    BossBots["BOSSKOLONTAY"] = "bosskolontay";
    BossBots["BOSSPARTISAN"] = "bosspartisan";
    BossBots["BOSSSANITAR"] = "bosssanitar";
    BossBots["BOSSTAGILLA"] = "bosstagilla";
    BossBots["BOSSZRYACHIY"] = "bosszryachiy";
    BossBots["BOSSKNIGHT"] = "bossknight";
    BossBots["FOLLOWERBIGPIPE"] = "followerbigpipe";
    BossBots["FOLLOWERBIRDEYE"] = "followerbirdeye";
    BossBots["BOSSLEGION"] = "bosslegion";
    BossBots["BOSSPUNISHER"] = "bosspunisher";
})(BossBots || (exports.BossBots = BossBots = {}));
var FollowerBots;
(function (FollowerBots) {
    FollowerBots["BOSSBOARSNIPER"] = "bossboarsniper";
    FollowerBots["FOLLOWERBOAR"] = "followerboar";
    FollowerBots["FOLLOWERBOARCLOSE1"] = "followerboarclose1";
    FollowerBots["FOLLOWERBOARCLOSE2"] = "followerboarclose2";
    FollowerBots["FOLLOWERBULLY"] = "followerbully";
    FollowerBots["FOLLOWERGLUHARASSAULT"] = "followergluharassault";
    FollowerBots["FOLLOWERGLUHARSCOUT"] = "followergluharscout";
    FollowerBots["FOLLOWERGLUHARSNIPE"] = "followergluharsnipe";
    FollowerBots["FOLLOWERGLUHARSECURITY"] = "followergluharsecurity";
    FollowerBots["FOLLOWERKOJANIY"] = "followerkojaniy";
    FollowerBots["FOLLOWERKOLONTAYASSAULT"] = "followerkolontayassault";
    FollowerBots["FOLLOWERKOLONTAYSECURITY"] = "followerkolontaysecurity";
    FollowerBots["FOLLOWERSANITAR"] = "followersanitar";
    FollowerBots["FOLLOWERTAGILLA"] = "followertagilla";
    FollowerBots["FOLLOWERZRYACHIY"] = "followerzryachiy";
})(FollowerBots || (exports.FollowerBots = FollowerBots = {}));
var SpecialBots;
(function (SpecialBots) {
    SpecialBots["ARENAFIGHTER"] = "arenafighter";
    SpecialBots["ARENAFIGHTEREVENT"] = "arenafighterevent";
    SpecialBots["EXUSEC"] = "exusec";
    SpecialBots["PMCBOT"] = "pmcbot";
    SpecialBots["SECTANTPRIEST"] = "sectantpriest";
    SpecialBots["SECTANTWARRIOR"] = "sectantwarrior";
})(SpecialBots || (exports.SpecialBots = SpecialBots = {}));
var PMCBots;
(function (PMCBots) {
    PMCBots["PMCUSEC"] = "pmcusec";
    PMCBots["PMCBEAR"] = "pmcbear";
    PMCBots["USEC"] = "usec";
    PMCBots["BEAR"] = "bear";
    PMCBots["PMC"] = "pmc";
})(PMCBots || (exports.PMCBots = PMCBots = {}));
var ScavBots;
(function (ScavBots) {
    ScavBots["ASSAULT"] = "assault";
    ScavBots["ASSAULTGROUP"] = "assaultgroup";
    ScavBots["CRAZYASSAULT"] = "crazyassault";
    ScavBots["CRAZYASSAULTEVENT"] = "crazyassaultevent";
    ScavBots["CURSEDASSAULT"] = "cursedassault";
    ScavBots["MARKSMAN"] = "marksman";
})(ScavBots || (exports.ScavBots = ScavBots = {}));
var EventBots;
(function (EventBots) {
    EventBots["GIFTER"] = "gifter";
    EventBots["INFECTEDASSAULT"] = "infectedassault";
    EventBots["INFECTEDCIVIL"] = "infectedcivil";
    EventBots["INFECTEDLABORANT"] = "infectedlaborant";
    EventBots["INFECTEDPMC"] = "infectedpmc";
    EventBots["INFECTEDTAGILLA"] = "infectedtagilla";
    EventBots["PEACEFULLZRYACHIYEVENT"] = "peacefullzryachiyevent";
    EventBots["PEACEMAKER"] = "peacemaker";
    EventBots["RAVANGEZRYACHIYEVENT"] = "ravangezryachiyevent";
    EventBots["SECTACTPRIESTEVENT"] = "sectactpriestevent";
    EventBots["SECTANTONI"] = "sectantoni";
    EventBots["SECTANTPREDVESTNIK"] = "sectantpredvestnik";
    EventBots["SECTANTPRIZRAK"] = "sectantprizrak";
    EventBots["SHOOTERBTR"] = "shooterbtr";
    EventBots["SKIER"] = "skier";
    EventBots["SPIRITSPRING"] = "spiritspring";
    EventBots["SPIRITWINTER"] = "spiritwinter";
    EventBots["TEST"] = "test";
    EventBots["FOLLOWERTEST"] = "followertest";
    EventBots["BOSSTEST"] = "bosstest";
})(EventBots || (exports.EventBots = EventBots = {}));
//# sourceMappingURL=Bots.js.map