"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.newPMCHostilitySettings = void 0;
exports.newPMCHostilitySettings = {
    AlwaysEnemies: [
        "arenaFighter",
        "arenaFighterEvent",
        "assault",
        "assaultGroup",
        "bossBoar",
        "bossBoarSniper",
        "bossBully",
        "bossGluhar",
        "bossKilla",
        "bossKnight",
        "bossKojaniy",
        "bossKolontay",
        "bossPartisan",
        "bossSanitar",
        "bossTagilla",
        "crazyAssaultEvent",
        "cursedAssault",
        "exUsec",
        "followerBigPipe",
        "followerBirdEye",
        "followerBoar",
        "followerBoarClose1",
        "followerBoarClose2",
        "followerGluharAssault",
        "followerGluharScout",
        "followerGluharSecurity",
        "followerGluharSnipe",
        "followerKojaniy",
        "followerKolontayAssault",
        "followerKolontaySecurity",
        "followerSanitar",
        "followerTagilla",
        "marksman",
        "peacemaker",
        "pmcBEAR",
        "pmcBot",
        "pmcUSEC",
        "sectactPriestEvent",
        "sectantPriest",
        "sectantWarrior",
        "skier",
        "spiritSpring",
        "spiritWinter"
    ],
    AlwaysFriends: [
        "bossZryachiy",
        "followerZryachiy",
        "gifter",
        "peacefullZryachiyEvent",
        "ravangeZryachiyEvent"
    ],
    BearEnemyChance: 100,
    BearPlayerBehaviour: "AlwaysEnemies",
    BotRole: "",
    ChancedEnemies: [],
    Neutral: [],
    SavagePlayerBehaviour: "AlwaysEnemies",
    UsecEnemyChance: 100,
    UsecPlayerBehaviour: "AlwaysEnemies",
    Warn: []
};
//# sourceMappingURL=Hostility.js.map